# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource ThesisOrDissertation`

# The UKETD terms https://ethos.library.leeds.ac.uk/ethos-oai/2.0/uketdterms.xsd
#
#<xs:element name="authoridentifier" substitutionGroup="dc:creator"/>
#<xs:element name="advisor" substitutionGroup="dc:contributor"/>
#<xs:element name="sponsor" substitutionGroup="dc:contributor"/>
#<xs:element name="checksum" substitutionGroup="dc:format"/>
#<xs:element name="grantnumber" substitutionGroup="dc:identifier"/>
#<xs:element name="institution" substitutionGroup="dc:publisher"/>
#<xs:element name="department" substitutionGroup="dc:publisher"/>
#<xs:element name="commercial" substitutionGroup="dc:publisher"/>
#<xs:element name="embargotype" substitutionGroup="dc:rights"/>
#<xs:element name="embargodate" substitutionGroup="dc:rights"/>
#<xs:element name="embargoreason" substitutionGroup="dc:rights"/>
#<xs:element name="qualificationname" substitutionGroup="dc:type"/>
#<xs:element name="qualificationlevel" substitutionGroup="dc:type"/>

attributes: 
  creator:
    type: string
    multiple: true
    form:
      required: false
      primary: true
    index_keys:
      - "creator_tesim"
    predicate: http://purl.org/dc/elements/1.1/creator
  qualification_name:
    type: string
    multiple: false
    form:
      required: true
      primary: true
    index_keys:
      - "qualification_name_tesim"
    predicate: http://ethos.library.leeds.ac.uk/uketd/terms/qualificationname
  qualification_level:
    type: string
    multiple: false
    form:
      required: true
      primary: true
    index_keys:
      - "qualification_level_tesim"
    predicate: http://ethos.library.leeds.ac.uk/uketd/terms/qualificationlevel
  alternative_title:
    type: string
    multiple: true
    form:
      required: false
      primary: true
    index_keys:
      - "alternative_title_tesim"
    predicate: http://purl.org/dc/terms/alternative
  contributor:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "contributor_tesim"
    predicate: http://purl.org/dc/elements/1.1/contributor
  abstract:
    type: string
    multiple: true
    form:
      required: false
      primary: true
    index_keys:
      - "abstract_tesim"
    predicate: http://purl.org/dc/elements/1.1/abstract
  institution:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "institution_sim"
      - "institution_tesim"
    predicate: http://ethos.library.leeds.ac.uk/uketd/terms/institution
  current_he_institution:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "current_he_institution_tesim"
    predicate: http://ethos.library.leeds.ac.uk/uketd/terms/institution#current
  org_unit:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "org_unit_tesim"
    predicate: http://ethos.library.leeds.ac.uk/uketd/terms/department
  sponsor:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "sponsor_tesim"
    predicate: http://ethos.library.leeds.ac.uk/uketd/terms/sponsor
  grant_number:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "grant_number_tesim"
    predicate: http://ethos.library.leeds.ac.uk/uketd/terms/sponsor
  publisher:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "publisher_tesim"
    predicate: http://ethos.library.leeds.ac.uk/uketd/terms/commercial
  date_accepted:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "date_accepted_tesim"
    predicate: http://purl.org/dc/terms/dateAccepted
  date_issued:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "date_issued_tesim"
    predicate: http://purl.org/dc/terms/issued
  language:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "language_tesim"
    predicate: http://purl.org/dc/elements/1.1/language
  keyword:
    type: string
    multiple: true
    form:
      required: false
      primary: true
    index_keys:
      - "keyword_tesim"
    predicate: http://purl.org/dc/elements/1.1/subject
  dewey:
    type: string
    multiple: true
    form:
      required: false
      primary: true
    index_keys:
      - "dewey_tesim"
    predicate: http://purl.org/dc/terms/DDC
  additional_info:
    type: string
    multiple: true
    form:
      required: false
      primary: true
    index_keys:
      - "additional_info_tesim"
    predicate: http://purl.org/ontology/bibo/Note
  ethos_access_rights:
    type: string
    multiple: true
    form:
      required: false
      primary: true
    index_keys:
      - "ethos_access_rights_tesim"
    predicate: http://www.w3.org/ns/ma-ont#hasAccessConditions
  source_record:
    type: string
    multiple: false
    form:
      required: true
      primary: true
    index_keys:
      - "source_record_tesim"
    predicate: 	http://purl.org/dc/elements/1.1/source





#title 
#alt_title 
#creator 
#contributor 
#abstract 
#institution 
#org_unit 
#publisher
#funder (sponsor)
#fndr_project_ref (grant_number)
#date_accepted 
#date_submitted (date_issued)
#language 
#qualification_name 
#qualification_level
#keyword 
#dewey 
#add_info 
#ethos_access_rights



##resource_type 
##rendering_ids 
##date_published 
##media
##project_name 
##pagination 
##official_link (link to copy on EThOS)
##related_url (link to copy on hosting repository)
##license
##rights_statement 
##rights_holder 
##alternate_identifier 
##related_identifier 

##library_of_congress_classification
##rendering_ids 

##original_doi 
##draft_doi 

