apiVersion: ENC[AES256_GCM,data:uUw=,iv:vHmasPeI8GymT5Fn5PotSisCF9/nOJwwbId3Pb7dWEw=,tag:m4c/AqNpfei9UXBPElfF4A==,type:str]
kind: ENC[AES256_GCM,data:HDnHfRo/,iv:P4cxzTaBNZXQPjKZdfGeFxwkwXgK3BMhB5LQdxJuaes=,tag:4fcf/FaN42gh5ZPTAalTDw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pSZYDzkLX6iRdmFWwNw1Y6YCGkfo8fYaLFdi,iv:wry1sp3TsEAxlX7QJw0AcFMYwxeHW7kMyrEJZvXJjoo=,tag:eseednNtK6Nj+7rM370WIA==,type:str]
    namespace: ENC[AES256_GCM,data:0JzQ0Of/6lZt2cvR,iv:b1MaobiNPjerRWK6ITFQNM4kDXcpQ31Iyrpf7SQuYIY=,tag:LhlA1GB4tUfSqlhMyJfccw==,type:str]
type: ENC[AES256_GCM,data:+IS9tIH7,iv:/g6LJ+La53TqyKSK2gMxfH1RZo81ChhAgMCmI/JRKbU=,tag:sFsayBl4esFBQ1DkW5YdoQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:12P2IEUO7EUcI9QFdPd4ZbgUlIlmG06HK4mPy/XkWDTu9NiJXAmX5g==,iv:R8t6huIvVt5KW7th05JlORRwI6DOkp3W7lsyPiIdAhU=,tag:tQ+xd687XTiT9uieA2254Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-27T17:42:15Z"
    mac: ENC[AES256_GCM,data:T2n4xCZ1Qc1lwdfMFnbaJ78pAVbwZ5+xkT4C9O5qe6yT+QT0UzvmszQBoZGiRdU+OBrD+wg52x41MDN4302HWWxm1Q7TxROnHQIGJKxJrsiBEFA2aOj4elOVvy2WUD6Iz4oc2Km3UACKOsbRHnY7vyFRSfqIIDhfrcQ4aM1rxm0=,iv:SI/TrLPx4gtTJc/4Y/NqFnVJLgQiE69wTouiYahN1ns=,tag:0HosiwXh1i6mpmOLGqeB8w==,type:str]
    pgp:
        - created_at: "2026-02-27T17:42:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6EyMwI1N4AyAQ/7Bnu68jCni4aG8oy5eYHTNale6J1r86m/SwACQu1ntVT9
            V0PrnXejeZKhWYxOTsl0ndUxu1v61WMbuooF0Z0DUl9QseuTwnpaNePNhahBfjJw
            YqU5bPzO+qnI4fuOc0XrOKWuZHEfeCG5FPLGcWCpeKYmeLUVHtFYfa67N7U3/IO0
            krZmLOqVMFZNrptbBobXUU7abyfKfj3/SEQa/30lnFgTnFG7RTHPL1LwEydqvZV+
            EsA4fQT/tLFXbaIdpS1k6MGcdoYFj0i/sf61WXt/fHNLC9vmZZzSI6mrwkvWqtIm
            dGdwa1KvI3RbfL9AP0rqgl47AgEpIzT5r7v3ELWhxiqwz8XbS2shKd8cyXLNUmL3
            F+LiSiTbtqdm8EvpRUS/D+hhPIw3ewVmMdzmduqgHQ6KqpaAb04li+Xt0yV6FkFg
            cWqJ3GU/Q2K4B8HU18gOb6/220v2vonLS8e9Ox/3WNRZMAgKK5+DuVZfkBsRBaVo
            0gv8UTIB+OQl0RjdUO6GBFL+GqSdLWmgfOq/fGdc2UVRv9czrehItK3N9YQyuskI
            2Y6xIJu9JB2eYnIiO9o/RJmSHoVz/zL2PHkfivlczA7yrlYlGr1bYUx8EW69Zkcm
            uuwv5p5jRQumTMayEla0MPjm6FWS48ub3kfaBPuASTwP+PafMvxwj4dvZtSrBXLU
            aAEJAhDGMwcBGi3cgOREzYp3RO5wkIS7kgx4AZV/UNzy6EjVQEJtEaiiuallPCbH
            ow73ECFK8EHf04ePKdk1VpfNrjkw+abZ9hMPbBWdERVPxiDilw8rfeVSEh0Ox62X
            J1hgbQxd9Sny
            =7g5H
            -----END PGP MESSAGE-----
          fp: 3B1B168B501A50A1A0D1174BB7D8F807265CA841
    unencrypted_suffix: _unencrypted
    version: 3.8.1
