replicaCount: ENC[AES256_GCM,data:Wg==,iv:q1C5rGN/lycz/bTLht9Gsw+8aJEdTqkifhV+1PXoyes=,tag:4SJ3JIDwqsVWbpi+eF8V9g==,type:int]
storage:
    enabled: ENC[AES256_GCM,data:NEmxDg==,iv:iva7VL3EphGUKGD54jYImmxvkK5UveRg/MuMGbF/Sbk=,tag:1MIt0uSSRFE2Wzb0rvQdeQ==,type:bool]
    size: ENC[AES256_GCM,data:PFRBxQ==,iv:0GTGMUZG/9Rvi6cY+7h5OCuVbRLH1PxtjoTOTg4FXbE=,tag:vJIFo3NYMEUOXbteegnLAA==,type:str]
    className: ENC[AES256_GCM,data:ugTx,iv:Z2Ywx/cOjvngz/9Sp8TDxcqT4YZpOUMZZPvR7wXeN9M=,tag:cEK4Hfc4fuLN7Kt5Acftug==,type:str]
image:
    repository: ENC[AES256_GCM,data:MNMH1UN4EuIwOxgrsBeQ9GjHK2Q7c1E=,iv:Kq1H/XpI/Qe9TkNjnoBTzZH0nOYzzvI31SECXepDcnA=,tag:YiHmLoEPELmnPZ+8+pqHtg==,type:str]
    pullPolicy: ENC[AES256_GCM,data:jiOqgdqbiWpoFPf4,iv:yMvnXgpEAupujUgvU69hxodT5nd9j4gwht1JuEtE1KY=,tag:lIfCPIJrUqlMM7dfJQu+Zw==,type:str]
    tag: ENC[AES256_GCM,data:iE77XtE=,iv:y6UhJN7nyotu6vSZPvekZAgtJGsYnLZGZ+JUFzucYT4=,tag:43YerLl5MzhTeUmp+ozQ7w==,type:str]
postgresql:
    enabled: ENC[AES256_GCM,data:tJrioso=,iv:d7Znsf2omyoYixCykM6TuPZcEXfgEbRXpuI6FikHgp8=,tag:qCl5ec9bfuQ9sEbB1psGdQ==,type:bool]
externalPostgresql:
    host: ENC[AES256_GCM,data:ZcZqmByp3nXdxuQ+OKMz2mRO,iv:6EljwL9uMXq9rLpoCTDKE24DIZcpayR7gsl8mgoS7Bw=,tag:psFAgAns5DpY3AM5YSXS9w==,type:str]
    #ENC[AES256_GCM,data:PXVmfynKOK3OlDTttOq6g6nQtx9TtWp2elH71ZaOImKVbQ==,iv:Jmroto3FcBvIoQTPl5Sxc5A7MbX93/S13cULf7gWyeA=,tag:pYvaUhwgQZ/koee8MRX5pw==,type:comment]
    username: ENC[AES256_GCM,data:cOcSXm86clg=,iv:Wr93j6IWLNKVV0JSYqz+1cHM9sfD1H76Iy/G/f9Hczs=,tag:g5q0gpYkbm7xBCv/Z+9awA==,type:str]
    password: ENC[AES256_GCM,data:WUDRyvfqWQv25gcrAVtaJKZWpfQ=,iv:PzdyOXkM0oYjpY/EPuR1zZtlwZV9AABFOeIP8lF7je4=,tag:zXb44di4wq4mD095PkFzig==,type:str]
s3:
    enabled: ENC[AES256_GCM,data:jCarFsI=,iv:geZmlWubx3I2EMHu1WLc1OOV3d5P5DQ9KNpSq9s5GUM=,tag:wnNxzTV4rq090qipFqdYrw==,type:bool]
resources:
    limits:
        memory: ENC[AES256_GCM,data:cHpb,iv:S1hL5Uzw0cnVDwNds+MZys8CQrjHrhSgXpg3vRG7Z3M=,tag:SEH30qpC38wh2QB3qLC5TQ==,type:str]
        cpu: ENC[AES256_GCM,data:8g==,iv:onjLahkVuY8bbgYiPPtpwUFg7wykuZxqIMjlig/1RVw=,tag:sTikbbtkdixB2ZLIGiNuNw==,type:str]
    requests:
        memory: ENC[AES256_GCM,data:CB15,iv:Nj0uhvhLo0DZsC6kz1swbT8aJHgt6n4AX9uYM9eNDp8=,tag:km+8vmGHVkvp2idTKAXjmw==,type:str]
        cpu: ENC[AES256_GCM,data:vg==,iv:zZh/khpfEw1FxxFTV8ktRHhG+FPP76qMQ/QDU0v31UI=,tag:mmXJzdXmV6FFutUzD8qKFA==,type:str]
additional_java_options: ENC[AES256_GCM,data:0EWB+DVtOVS2g8GAt4ZLAwJUpUQfE488De6bRnBj7G6vnIXzWNeC5nuwBtFqEFdcGyWQ3mnz1u9BUI/VwX6A3ZjE6DFpjrBILXTjvxGjq5S9X50Ztm5nu+JhsgvHtIBNZ/rvJpjme6sAFUrtXurm8dzTpTHOC0GfEZ8K7QcCj6igOzUWboWnX+QwDwZIUOjGk+pVO7t7BzlQbyMl8OHcm+nXOc0q2E3yrvWt+IiW4HkbrRU=,iv:dRCr+/3yE6aANZCw3LBeDFAOllphU6BA0/A3lOUg4+g=,tag:zumacyOCJsuXc+HzHs1BpQ==,type:str]
#ENC[AES256_GCM,data:4l38sdVy8Nn6qfvlbOpY2Jn969VmyiaNp6+39qcfTz5Q,iv:q0CmWOK0YOEbgFfbwRkxw/AOcgAZdyoDhkj4sqbnIhI=,tag:AYJxovC9eCeqDb0Z5nbaFw==,type:comment]
#ENC[AES256_GCM,data:j8iqAlaeAJToKhYeE5FRP00OHZWre1BTk5Je,iv:vAT/a4bmvPF5ruhzvSGpW2e/MN44WPh7kyYQyy79rGw=,tag:AqhbDXN2i6XhoMrgbMRjdw==,type:comment]
#ENC[AES256_GCM,data:rW8VKHd5BeRpa+DA6lW7yyyX29yZzfVVAbQMKJFHCaTx9wRDj5D7XnZQaSivoy4SBpXgF3sdQpojazQJ6e+gBVfwxvo=,iv:Rh+WSFcBAFIBrIoMX9Qixz6i10aJDA+4GfvW8GVzFZA=,tag:HO9DIC+yVl2hF94owLmOxw==,type:comment]
#ENC[AES256_GCM,data:uh0TVVAtBZfmcHjZ9x5H5KaqGevTKAGaUrCTyGy6wQzriNUCAb9MCGLHYzOQutHKGOeNEzBypYaovQVHK6AhfiVesYy0K4WQc5Z8,iv:TSGHiQsb0GE13NENTNhAGdJrygFFhgXxOo7jOC3MvfA=,tag:pdq3I4Z3gPUWNccPhknjZA==,type:comment]
#ENC[AES256_GCM,data:KSJO0mL+zu48eCNH92FrVlYB7tq/qQhecWqfG/Ayyd89KbOVHXQeewaqBhyGgdPLoY3lY54iCTQMugzS17umC1iksTeh0+aVtklr,iv:G4WE/Af9to0twIrH9a7RnXCP41dsxX2jD81JEzKfElM=,tag:mIHtY1fubxdwnCKTgN5QoQ==,type:comment]
#ENC[AES256_GCM,data:Kr4FEPdAOD7Is7IPThDK2lKRE9G0bcgpCP5DyWiglqhQUVFoweoYVkAZEm3+bkkm7gAHVBa7GntZvURjlb5caLYiADNhpXmqsUUW,iv:7yjKQhW9YXsTyhhQTAx2a+BSSWlfLhyPoDOga4eRMnk=,tag:bL4mBkwNkIOGHbPyeXFodA==,type:comment]
#ENC[AES256_GCM,data:igzXHF9QeEgOAxrL3+ZbPHaGBkLrm/6wU1uFn2odrJUFpdXSFSUtEkHZXncg4eOD2D3E6FNWrrz0/RENEzV5tXVZ3ZXPBHS+ppgk,iv:n8O7xygmKo9XCLEd3RuzfvdDTdcNfzGmg3C+ZKUSd9U=,tag:4vSZZ8aIAbX0hO8rjMBtiA==,type:comment]
#ENC[AES256_GCM,data:T7De/x/LzvZMG+SJuHODsrNQ6CM84fgYYrU1biAPh9wGSe46QzMW5WfVN5JkRuBiKzAPqgZnOJtAUKzqdSB5NjF4pRhSKmehCsTh,iv:m4PDtA65p2X5jVq0sRJ1B+OpPZgEBhzdqpptEnWXK1k=,tag:nhNXqxSYi+/9KhlYjMlS9Q==,type:comment]
#ENC[AES256_GCM,data:qnAsT8ytg3rA3jWpUeeqZWrNYQK8q4Grww/Qd3Av0nuPDMHmVaQ9C/V9vKhEk3cO,iv:HtqaTm7AEdkMkcBstAS7sv57MQwk6JWsp9jlqiOJBHU=,tag:63LB1Oh/5LCmZ3AVes3nLQ==,type:comment]
#ENC[AES256_GCM,data:n/QOkuFOnksGIsE3wqvp4mv0YqfByd1VyRTB+iQmQ+t97MHZGXOx1MHxIRXW7M5dLtu1,iv:io6Gpyh+DbEmbVlHSzJNIjMJE75qDOoooi0N9Tm3Op8=,tag:IzXcbrm8/TMyZKsKL7d+Ww==,type:comment]
#ENC[AES256_GCM,data:av3K2NNKb64jlSDtbJjleG7eptisTTCqdVbJHCkaRGNUKLM4hasG5xgxlxxlFWHVDINFsAw=,iv:6fTOi+g8auquIiAfVjVFKkURXySzfxBlIKgAqA1wlew=,tag:NnJ8EelSVZ/V6nGz2EplZA==,type:comment]
#ENC[AES256_GCM,data:KDVba9x6vb8emc17DF7OkjedCNGIPopGrTd3a8RCt6PYaZEXptqIW4aXnKSkhSc=,iv:j9ykWVi+5IKaS268NQGkqHWO6XDYwGsZuUwooa7iYl4=,tag:696Zgh9A1q0XRZYgv9Z3hg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-27T17:42:15Z"
    mac: ENC[AES256_GCM,data:nEr1Ufa7xDdtLPjBdCH2EdZo4wIZdu3lobicrsD6HtQDiTwZesFPvXzk1kdrRXYfq6BxKSfooJZO/SlG0wVr4/6WfRQqlITjNTZFdG10mbBTZdD6Txfz0aTSV1x1VLj5q9O42iRidr7BKeyIrXXUToXLO4QOcjZc27xkK8V4+Wc=,iv:rOPgS3IByiYTAVO6f09KCM2YxUil8KHAPfwkwh7hfxg=,tag:2prOVdshR57kUDijlWXFgw==,type:str]
    pgp:
        - created_at: "2026-02-27T17:42:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6EyMwI1N4AyAQ//atK8IMb/vvGTCTlWxS+fHe6/OzIVyR0juLy3b6MH0953
            GZxhZPNV4sZuKr6/EuZyr40AmhkQZ0HEQYPlHSUQ+DXy2mgD0sOx4J1Q/E+nEcH3
            QKFJ8EssnKhFI5gnAHTXFQm+QQYn1+bfERBXMbqAhWySmRq7PYvNU6BNwkbhQMj+
            SN8wUm+nqYWctJC4pkZUz+WkCEqG30m5/r0k0l6ivum+qY7Z5cyBOw23Nez3eayC
            2CZUhX57zhdZIOgvxMWNpStOATBipN8v/k7GV88bgRiH00zoR2Ki2fPdY4bmISA3
            UF8K2ZuDy0oyVqzqCvInK+KljnyKBbpTVywEDxFtE0Zjf8tUn8QAXjn4fIX/u/CZ
            y4U06ujn4+ceGd5L0wGLJyh2SAwON4DKdYhLhECl+cLSpuh6Rem8d2vDz7YRbdYv
            d6xEfF3hIFCz47QiHXeEmp0EG9T1Nd7I/Xn02XixwX2zt8GERpJUYu4O/Tf7a/th
            3ZW5/Qvv5ttbfdTt4DnEQbbSR2agn3N0iXjj2CGt4/IgfU/bSiG32iynUik5rM11
            oB7d/O2f2+L1/y+DPkHzfd6909XGuHFEZVfhJ7dTZQdg93p9XMso1VjKU5NUdSqv
            Y5sywp5knqmiLY+iSgbzOOaPQZMvPCt+vLZCtLleBA7ybIKiefQm5o11Ool4lezU
            aAEJAhBGVBu5F50X7Eiy8YQ+PzJcUTuQoQCcTx1EHG8dfqJwojYgB90FSedUR0f0
            /eOXKH1WZLf+TjoqL3nmd04WyRkpRmvaOEXDw5LFkrN6S5BTJGQ2dPdiyqNtlu61
            pBzuWJaBdO+v
            =pU+a
            -----END PGP MESSAGE-----
          fp: 3B1B168B501A50A1A0D1174BB7D8F807265CA841
    unencrypted_suffix: _unencrypted
    version: 3.8.1
