additional_java_options: ENC[AES256_GCM,data:7WtEoYZus8XSxPNV/a14NU9O2bGcMWVAqKVInjguSkgXN8LiEuQ/DQ7mqrxXPvcKkQgz7R1tXYdzEmje4z6IHF1trXr4K01LLIiAd9sRRfaj4ysyFytgJto/pfvv08U8dY5a5RKSVpDzsvJ9YaJMyrtm81Z0+sQpVdHlZm/XrahkutbiP1HNoQwl+LmvnMweU5dlLO0h9Q6tDsVBr3zfU2HvVXh0TWMTxbX0usGR6LW65DY=,iv:6JSD1jXUEi5Opn+6IHeo2WaA+kQLq7BP6e0HM/kdbNk=,tag:ZM3qGzX6YEFP6HfmOKni5Q==,type:str]
externalPostgresql:
    host: ENC[AES256_GCM,data:gHVY8h+0Ki5vrCUYXmyutPo=,iv:ykwviPx+/niT40B4pjWgA4DUXHxmumkpaY26tiK7xnI=,tag:UZSqynSYJ/Ei2sOksioGbg==,type:str]
    password: ENC[AES256_GCM,data:WH4CbWJm7xsnuOWHOMt2f9ytIrs=,iv:ONWxbMsFFv41FFMxks4NhT/bVnAP+ASjxbuJ457Ktuo=,tag:zXVwuJTJkOlZEILeWFop6Q==,type:str]
    username: ENC[AES256_GCM,data:kzLsItu5ueo=,iv:7LZHW6ICNBNw3uWfcxhPH/QlvXLSO47WJZZuGbGN99o=,tag:Dyzr+iDbZip235Ellyax6A==,type:str]
image:
    pullPolicy: ENC[AES256_GCM,data:ERltv4HjwPwsdLmI,iv:qHwFtW06w5VPvtn9pkyGG01oDFXss5TCXejdTgH56hA=,tag:nI8q7J3v8KD3DG3+zGBwyA==,type:str]
    repository: ENC[AES256_GCM,data:f8kU0jNYKdfnk2i8jmmBPQ6COIAiqZI=,iv:k+Rn41cZoRMK/pslRKahk7YYP5q9lg8yly+ykEzb5Sg=,tag:2NJLtonpP1i30CUXlTdwIQ==,type:str]
    tag: ENC[AES256_GCM,data:u2yUANI=,iv:NQp65s2Jc9gVpeqpPWCamlS4haeuptkzxQ3Q2P1YjkA=,tag:Hu7d1Q3StWmmaAIkN7lO+w==,type:str]
postgresql:
    enabled: ENC[AES256_GCM,data:2dqyG5o=,iv:dUoy6xpruMycLHLUzO25HLtzr+jjTwTPVS0Hmpg2xi8=,tag:KXL3HZGJzntbyTdlb2g6nQ==,type:bool]
    image:
        repository: ENC[AES256_GCM,data:UX8QhmKmEZRoWcCcDdz/OquFCmPcHbth,iv:hJXLu+yfSlDmI9rRZ+8RwFs5jE2HWKe/nhkX4UhhOOY=,tag:hwZxKTjJqTK2SdQegt9lTg==,type:str]
        tag: ENC[AES256_GCM,data:wsbQvte2,iv:WOQs62AmoQiuejcc7TmCL4XEJu90mlBIifWphIEbfY4=,tag:pDKjz2nDYu6UOkTG871Q3w==,type:str]
replicaCount: ENC[AES256_GCM,data:Iw==,iv:mTqri2lfp6jjoOcZvwUBkXXPKjHdFCgVT6Gz4/AiEAY=,tag:m6yCCwT28sxkgCJbasvsBQ==,type:int]
resources:
    limits:
        memory: ENC[AES256_GCM,data:Ev6R,iv:GXMuK+szK6cY2P8Oy1eC1nU8wyyFn1vGIPBAlny/deo=,tag:5vwQ+SLNrZM6Qr9atiBAFQ==,type:str]
    requests:
        memory: ENC[AES256_GCM,data:ElRv,iv:iRUw47aFpeKpA0rINqKotG01LgggFtUIZCwbjmALoYY=,tag:r1QN1Wdgw7gW698qRjGHmQ==,type:str]
s3:
    access_key: ENC[AES256_GCM,data:R4BG6oFNnx6WEy5yzcPi4zFphkg=,iv:dQ2buyMiB8TIz8bM5CJF6p/8gR9m5y7i5Cx5CWZS5U8=,tag:EmB77lSGvjgxEEHDcd9h1g==,type:str]
    bucket: ENC[AES256_GCM,data:+8HQNed1cr2sdj2Tu8hmT0RW0PoDPzM=,iv:jE5zjekligAfER7zEDkufee7WJmQ5hC7HixrWzhxG+s=,tag:+yxWKnMo2zuKk1FKp166LQ==,type:str]
    enabled: ENC[AES256_GCM,data:UXWvRg==,iv:obK84xqXU3kP55imddi4OutYHkGZEKqdlh2oSg56Qio=,tag:RcDXJoxxVLGMsQ1WrtuIcA==,type:bool]
    secret_key: ENC[AES256_GCM,data:JfMs6BpdWuKDLS8XoVoPGoYIy/QEI4idnWTCqNlINy3/k5LXOomhmA==,iv:6pKJHQf6uTvJNhxzQDFCnxYPqmT5MZuEXzxWbIJDsBg=,tag:M1xXrvgfAk45AFIeN3nFew==,type:str]
storage:
    className: ENC[AES256_GCM,data:qIhB,iv:nj/BmcrnV5FWUKwHF2gsUIUlEcaOOJODk/sXHWSrZ10=,tag:UfsOTfUlMaJUF5HyU42Q3g==,type:str]
    enabled: ENC[AES256_GCM,data:lwf5FA==,iv:9EiIEsjK8jxoFi22Oe0PfAdjZO2WmvTbKJo15raH26w=,tag:JnlqLNjZ6j/2Ezjcu6dtKg==,type:bool]
    size: ENC[AES256_GCM,data:9MJOuEc=,iv:RKbCifw+h8JkvLcHVZGhTn02Sps3fXuayJ3ozMejSIA=,tag:TpuCGBxp77cDv8JrpBSiTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-27T17:42:15Z"
    mac: ENC[AES256_GCM,data:7lEkJxUixIZk8up+dtKZsurE2EsSHhUzp4EO+mh9cWvTqfGQ+wya1/iyslVhis6ltv1eosc/0bxQ0nq1knZXYL1nSC3sl4Na4uzk5FjJwaxmhtls+Fx7cCCq0/utHEx6LpOSY5yaF37Q8DgavUWmwZBLGrXQ33NEwom4h5Fm40Y=,iv:prh4Jse3CWapddW9dW1BjCufXXcsrNPfHdbSbpTvhnw=,tag:6yaqphxsdzfRhhHFKBhYAw==,type:str]
    pgp:
        - created_at: "2026-02-27T17:42:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6EyMwI1N4AyARAAjhRK2U1Sz2YZ8WT8+TZfqZSULnNWhp4+mpX732CYKaO7
            +uGeLxCJo/hcVQelj4eEjKPKAo9IkQ9GPUpOgcMwtptv5p0JS3iCIp5uEfaoqUSf
            xUmxlwNOsLPswUfn8L3vWbolcYqc8dzxCI0KOV7XgnaH7N3+Wq/xOxjxytJsZ7qh
            gBV1aK+52P1IauNEaQAF85ceg1gU73EgOIaPM7XC6bPf9oL+0ttDYr6eAUdP6wSA
            aH5mGJbIguClGixSGjRCkzNEMJjM8EfFOvflLzNduI6QFNvHWWJHZRitcF8IRMJ5
            kBovXGZovHxpnjOXjX6syYGovrG9muxeb/tWc9AXBvqgiaWA1Hu5K4HSgK1gyB64
            O7P5s0A8NpgxuHsIsqR1flMQdMjVHcL9HCB6m4bCBkEvRCqQPTGaKCgf9DJp9WF0
            a4xbQVDl4BR04z1rwRBeEnRxxwnj4nydHEblg4oMDkT41GAfRcZf1yoW37XzmjN7
            bGDGTxPvosN6O7avVNDNjjpV3RZCQN9uXDRQHcJKNoEgHjpVB6Lzen2ultvrU4gS
            trM2R7CRmSaneDyH7SP5HWKvyB24D2TBAranJY6iVL8WcDpYA7FhF590uWorVt+p
            pdLfrC6EIfJH7PekSnM1NViQNvu1Fq6tsTmoPDuD+Ynx1ZDrGZ+brhCNFXf9dyXU
            aAEJAhDmQjkxWhRaeHcG4NkI5lU3H8QGRMph7Mam88rfJWuAKvO5HBZAt1mwNijj
            aUgWdalEm0WEkGfvcAwwrm/8AXzDU/mdSv9WCbNoH8LXyT3g0TVq6cco8nkAKbKD
            fvCRgCJjQxJf
            =rFAv
            -----END PGP MESSAGE-----
          fp: 3B1B168B501A50A1A0D1174BB7D8F807265CA841
    unencrypted_suffix: _unencrypted
    version: 3.8.1
