apiVersion: ENC[AES256_GCM,data:ysDygLOURAHpEqSUJ4c2iZEI,iv:in6bddZ2A1HgdUWGHDuswJvgTXUiXiaz2XZsi7A7LEw=,tag:THiqGueauqWpzRSXHxhlrw==,type:str]
kind: ENC[AES256_GCM,data:VBW/H12UZlgycPMPpQ==,iv:Fw/R9HBQZzkN9v4TY0QzO+7opaSbXrzXh6xbfm+fWWs=,tag:IUl/C/U1qcDCgwq3fcqfhQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:djRCWkSLgC0Dg9mA2I7Sn2dYwRpEUOAoxn0=,iv:OsqNK9Ux33vz3h2OCgjjY5oculhmwHmsZhllG31vjrg=,tag:Mq+ncsxnysbNdR90WZCbSQ==,type:str]
spec:
    acme:
        server: ENC[AES256_GCM,data:PjHvbNsjWqSUaV3x/tNwjs2qVfNRWpNJivTWg5zTnrZj4FT5XIFm9OOkxVnUJA==,iv:rrROgNZT30YHN3X0i8ri5UXh7dhMpjh+ve/41PCFNDg=,tag:w1DbD8+gSox0BvkLlDc/WA==,type:str]
        email: ENC[AES256_GCM,data:rWiTHtbClXkeheM+vnk22jHm,iv:2H3RUJkZ1XGUEUAsJQrI/YnWHU1O8Nv2DGFghfRDXC4=,tag:gAWYvw4zxLRAcoIUURAGiQ==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:8DXb13GQl+zv70grL1OValbqVxrjTV2WC+PEz8Cv,iv:7l3Gbf643gmYEnTOWiTHYOgg/olAb8GGMta+DGDYGws=,tag:bIA/sldYXdJagHBtolVLJg==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    email: ENC[AES256_GCM,data:p3eQTijurbfu9E8X9FffzdiR,iv:64trtNdup1/CGiZEwrTRr+/BI8aLjfA+Vt9YFcfisJ4=,tag:j0OfG498ki0b1MNTvtB7Jg==,type:str]
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:q2lkj1sgS8GNGi/pcvTiftBkpH6Jval7PxI5,iv:qLelwFKcyMqjaf1IqwqwTsop9ZeYzC21eyxHYNMqOZk=,tag:xgtdki5nfcz4zE057N+c0Q==,type:str]
                        key: ENC[AES256_GCM,data:ySwa04g3M/mK,iv:sTx7eBRgpqRMusmAzgarT5Nee7+/ZByBK0BrBw+d/S4=,tag:XIzziUtVmi5zEKW6omCPSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-27T17:42:15Z"
    mac: ENC[AES256_GCM,data:vO2mcX+7Q8hOa0ueDD/2ChhFziNIbF262HwNK5jzr2whaPIvfIvWe+raRWvJxHSdITSWy/7zMMw+KyA+v2UrXTdXlBmCe60NEC7IaA7mMzPf6M+/jrsa5RQ2XrvLvaGvWPME7qep9ShdjAgG/tTylvqWk8W2c6RQdUisSoebsIQ=,iv:ZK69W/C7xxVm2RYykYral3J5MuuqyM9+9PvjrtOlpLk=,tag:lLf4yNUE/BeqIHTKoijzNg==,type:str]
    pgp:
        - created_at: "2026-02-27T17:42:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6EyMwI1N4AyAQ/9GkeWEqqEshmQYE1rmXBUzLlTTHk9vHTOUbQoZF/T7Y9T
            00GfeGgm0uJbDbz0Z83fZGkEVOt1bvBpuPHBuxtgcNgFoZV31DXcAARunI2F/+jE
            FOdFXP6JYxvytJC681ezz1BFhnrNIrWQOrv+REBFp9x3kgkxZyWtkPSDzQMRO6X2
            Qu0ohkmjhh2fTP/dt0iTBLUCGcZWQQeTcaEdAinVwgGwQnxPA5ywGqVSezKh8mBg
            bPWOqFGV/vml+Y3+fjPZhlcnWgPLkFRiOvAJ4Yo27kdsfASLJJcOK0bSiAlskuW7
            28w6l0JH0blP4qHi1aOkRz4MxibgSFtbL5oz2gyfSUJK9OObr4AJ9ssAJ2A5S3gV
            q+DH1aq+pbavU0kVIqa1BFarv6ff3STUcp0Jb59HSwrqXPjNd/QvANMWoVUwBT2N
            5nHJk8W0JmxK7Ndll2aXmYubFNE3k2cSG4KxWCUqECP6UOIKh3LDuazh+QNCJAq0
            hBP7MDNW7OGw11FB4bqP7sg9IcepmCLSebr2b6w9A3SuHAmUaykFeejsJRu+4X2R
            LFPWxr1LkwEbUdQqa6M9R7bcEAmTAqhFfUy0IGzLtw4fxkDh7J1eX6DcZeyh228D
            9eFq9yKMc8/vRgwaE+044V8iH/vXbtLBs9iCewExaer8vmPiu6RHApmm5XfCLyHU
            aAEJAhD4GovrxB5bNDWfXgR4ze7feTDorD81u0rd9N5aIy2hbJhOdEIrGmr4w7vf
            apfl4hxCQjBftDY1BNXw2IU84mcHOVVZRe7lQHxvtaKWOZNuWSDQWKgS7egkcRY7
            aUrunnpw0E7J
            =dYIh
            -----END PGP MESSAGE-----
          fp: 3B1B168B501A50A1A0D1174BB7D8F807265CA841
    unencrypted_suffix: _unencrypted
    version: 3.8.1
