apiVersion: ENC[AES256_GCM,data:Cuv0wbCNHnCu3jgSfoNhdjrm,iv:+033OVkFr4qj1eP/WpUFc+pV+OsV+BzzNswowkosE10=,tag:sjPYM7VtXDSbv7j6EBHRPQ==,type:str]
kind: ENC[AES256_GCM,data:azmYjNQL5qv/f1J83g==,iv:/JzNC88swMyHtnNMMpXRk2nTgV4MQDqSN+hjhq/7VzA=,tag:J4dUBRcwtstKnDWAjBEvIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:McVDQzrGzogccIsKxrldKA7cYYuPP4CLdgM=,iv:DtQ8fWAZIcBJ/3zJUq0LmLJp05dVp9el+yKlF2q7Xbc=,tag:Om8bzIA43TRV7+MOsxwI7Q==,type:str]
spec:
    acme:
        server: ENC[AES256_GCM,data:MVINnGo+OW4sy/aa2S9UokfCJgT2nuCt7siOvsBOX6DXKhoEuLke2C7vRip+OQ==,iv:a7BanUPlqfGxHQFO0VQONSW0OJ1gebhTFXd1k+eXN4M=,tag:XIpWbqruaSvvna/XUF0hiQ==,type:str]
        email: ENC[AES256_GCM,data:KLoZaX8y9/b1ov7qPrcOZ+IV,iv:Hx4bwmvOP2d5f87rqluFg3/ubPIJRDjWwjdgTAV4Kkg=,tag:nR4m1czJq8GwiUP4MMA2dA==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:OisFoM//uKgCbYEKKJFFpZl3R2qVejm15WGUR2D+,iv:0/k/Y1Umd1RXvw4AqMbuJ0bgEtIKQbWyUtUFPcMJ8x8=,tag:pqDUT+8y5GqQDQoLeORk5Q==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    email: ENC[AES256_GCM,data:GnYTosUahX+RaSUnz1FLCshw,iv:+XSzkWRWaLlUxVHesgsAJTbE43X1LcEJg5upJ7MBQ8E=,tag:fL1sgFmpIms1e2W5slDWiw==,type:str]
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:iopoxowwGpOQg8wvSG0ECAwOWqTMGGC2yh6P,iv:bYTpwws5FnodaQjVC5Q+ChNshazbpraBKExb8gjqwMo=,tag:ue3w9K1W8/fwZXECs1hDgA==,type:str]
                        key: ENC[AES256_GCM,data:Lsuvs12FItE7,iv:k847infpMWBFeNxLpxkkKv+zO29dhwPJGiQeltddJVQ=,tag:BYj045DDISlhjC9HWhhrCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-14T21:12:47Z"
    mac: ENC[AES256_GCM,data:Mbkw+UPEM8Vo7VVjX8MvfPfGF91cpExEhJKVI2wGOQHaShfQPn+F45J54Dpy4I1fl/Nnyy5dn+gv/lsluad1zIgkm6nGBz5qMKobfXSRk3a7SR9gclX8YHdVrstMhlk91UpoC9OtUkXkojJKKnG17qTsL6qI3qXizvdxPST8HMI=,iv:BgVgEte8Lhyid/WgysOyk+/rDa9zkb5NsEuPZf1l2rY=,tag:km/n5uXEDMpatdDsWHy/mA==,type:str]
    pgp:
        - created_at: "2026-01-14T21:12:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6EyMwI1N4AyAQ/6AjUewbqmGqm77E/m73gh7nabB7VhXcDD9LZ1rqpBk6KS
            AhmZRhOmiRhI5tA8R5XkKkgAQa4N/6AORrxijfTfAEkkjCOyITwG8sqBMsja6c8/
            cEAjJM5GFQq8Wy7efW69dL3Ose1gTtP6PrL5520MV4MJ0k78ZKXZ8FQQohOWx8bM
            02wHxyLp+R6M7gLPxq/sNOcnAqN4yeqQuxFsQW5YG32tNoUJ+xcVVTExFik7elMG
            UFPPBrUagBCcuyEMTECuZXBiC0Kh5YZwIhfa23MPruZM0bDG8nDWNU3iqn7RdlVm
            imFpCD7YU892ajRLr68dl8YeKMdCR2t7mL+BnSYVbJEAcYhz237FBBxsrCLg5ubh
            cT5aNchq+UWb7NLcwVx2qX4dav9nLa2Z1fdejIFm2rGMFoD7xap74HBbWcgzPRhN
            6iAjZ8ScO5DzeX6doqeCRWyKqHvxhmPfr8d1jqHIjy5hdme9U1vg2MbgbTcGYlaC
            eRzJMpie8KbvSCIhFHKR5C2+BeZRlFMs8P3SkWzg5SonwcDL0uTuBCf2MIuN8Acj
            TH60XQUZbUOWl4MnyKUfLEBeBYHwhA/KZG0CFR8Naf71yM/B0yF3Ug7pLix4muOZ
            7kdLYo/zn7p32O9BgvBrA4fn1/XmT/aqDI2pCHH2A5e11Zo6Wy9KWI5UHZHpqzzU
            aAEJAhBPIY7G+Vf5Jkao1t0F+ftNGtMtLDp62+2OYUlddfFoSLuS72R5tttvC/ww
            bb6u+Gnb+t0T0H7r50dM1A3B9GIVRD5vxGDLHKEKoIamX+3mxHlii14Ami30CTd6
            8tByCouLEvpN
            =xyMj
            -----END PGP MESSAGE-----
          fp: 3B1B168B501A50A1A0D1174BB7D8F807265CA841
    unencrypted_suffix: _unencrypted
    version: 3.8.1
