# Generate cluster configuration YAML (fixed key order for stable diffs).

data "aws_caller_identity" "current" {}

locals {
  cluster_config = {
    cluster = {
      name        = var.cluster_name
      server      = "https://kubernetes.default.svc"  # Local cluster reference
      environment = var.environment
    }
    aws = {
      region    = var.region
      accountId = data.aws_caller_identity.current.account_id
    }
    network = {
      publicSubnets = join(",", [aws_subnet.public_az1.id, aws_subnet.public_az2.id, aws_subnet.public_az3.id])
    }
    s3 = {
      postgresBackup = ""
      fcrepo         = ""
      logging        = ""
    }
    versions = {
      certManager      = var.cert_manager_version
      externalSecrets  = var.external_secrets_version
      nginxIngress     = var.nginx_ingress_chart_version
      postgresOperator = var.postgres_operator_version
    }
    sizing = {
      solr = {
        replicas = var.solr_replicas
        memory   = var.solr_memory
        storage  = var.solr_storage
      }
      postgres = {
        instances = var.postgres_instances
        memory    = var.postgres_memory
        storage   = var.postgres_storage
      }
      zookeeper = {
        replicas = var.zookeeper_replicas
      }
    }
    features = {
      logicalBackups = var.enable_logical_backups
    }
    storage = {
      efsFileSystemId = local.efs_id
    }
  }

  # Deterministic YAML: same key order every run so git diff is stable
  cluster_config_yaml = <<-EOT
"aws":
  "accountId": "${local.cluster_config.aws.accountId}"
  "region": "${local.cluster_config.aws.region}"
"cluster":
  "environment": "${local.cluster_config.cluster.environment}"
  "name": "${local.cluster_config.cluster.name}"
  "server": "${local.cluster_config.cluster.server}"
"features":
  "logicalBackups": ${local.cluster_config.features.logicalBackups}
"network":
  "publicSubnets": "${local.cluster_config.network.publicSubnets}"
"s3":
  "fcrepo": "${local.cluster_config.s3.fcrepo}"
  "logging": "${local.cluster_config.s3.logging}"
  "postgresBackup": "${local.cluster_config.s3.postgresBackup}"
"storage":
  "efsFileSystemId": "${local.cluster_config.storage.efsFileSystemId}"
"sizing":
  "postgres":
    "instances": ${local.cluster_config.sizing.postgres.instances}
    "memory": "${local.cluster_config.sizing.postgres.memory}"
    "storage": "${local.cluster_config.sizing.postgres.storage}"
  "solr":
    "memory": "${local.cluster_config.sizing.solr.memory}"
    "replicas": ${local.cluster_config.sizing.solr.replicas}
    "storage": "${local.cluster_config.sizing.solr.storage}"
  "zookeeper":
    "replicas": ${local.cluster_config.sizing.zookeeper.replicas}
"versions":
  "certManager": "${local.cluster_config.versions.certManager}"
  "externalSecrets": "${local.cluster_config.versions.externalSecrets}"
  "nginxIngress": "${local.cluster_config.versions.nginxIngress}"
  "postgresOperator": "${local.cluster_config.versions.postgresOperator}"
EOT
}

# Ensure the cluster directory exists
resource "null_resource" "cluster_dir" {
  count = var.enable_cluster_config_output ? 1 : 0

  provisioner "local-exec" {
    command = "mkdir -p ${path.module}/../cluster-config/clusters/${var.cluster_name}/resources"
  }

  triggers = {
    cluster_name = var.cluster_name
  }
}

# Write the config file to clusters/<name>/config.yaml
# Uses fixed-order YAML (cluster_config_yaml) so key order never changes between runs
resource "local_file" "cluster_config" {
  count    = var.enable_cluster_config_output ? 1 : 0
  content  = local.cluster_config_yaml
  filename = "${path.module}/../cluster-config/clusters/${var.cluster_name}/config.yaml"

  depends_on = [null_resource.cluster_dir]
}

# EFS StorageClass is generated by bin/sync-cluster-config (runs before every bin/tf plan/apply).
# It reads efsFileSystemId from config.yaml (written above) and writes efs-storageclass.yaml.
# We do not manage that file here to avoid state churn (local_file.efs_storageclass was not
# persisting in state between runs in some environments).

# Output the config for reference
output "cluster_config_path" {
  description = "Path to the generated cluster config file"
  value       = var.enable_cluster_config_output ? local_file.cluster_config[0].filename : null
}

output "cluster_config_content" {
  description = "Content of the cluster config (for debugging)"
  value       = var.enable_cluster_config_output ? local.cluster_config : null
  sensitive   = true
}
